services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app  # Bind mount for code reloading
    ports:
      - "8000:8000"
      - "5678:5678"  # Expose debug port for remote debugging
    command: python -m debugpy --wait-for-client --listen 0.0.0.0:5678 app.py